Repository dogVelopers/dogVelopersServer, pull requests merged in 2022-02, with the labels that each got.

#2 [#1]필요 패키지 설정
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/HofController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/MemberController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/ProjectController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/entity/Hof.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/entity/Member.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/entity/Project.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/repository/HofRepository.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/repository/MemberRepository.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/repository/ProjectRepository.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/HofService.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/MemberService.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/ProjectService.java
Labels: feature

#4 [#3]requestDto , responseDto 생성 및 , member , hof api 설계
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/HofController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/MemberController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/HofRequestDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/HofResponseDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/MemberRequestDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/MemberResponseDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/ProjectRequestDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/ProjectResponseDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/entity/Hof.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/entity/Member.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/entity/Project.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/repository/MemberRepository.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/repository/ProjectRepository.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/HofService.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/MemberService.java
  dogvelopers/src/main/resources/application.properties
Labels: feature

#5 [#3] 조회 기능 제작, application.yml 추가
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/runConfigurations.xml
  .idea/vcs.xml
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/ProjectController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/ProjectRequestDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/ProjectService.java
  dogvelopers/src/main/resources/apllication.yml
  dogvelopers/src/main/resources/application.properties
Labels: feature

#6 예외 처리 및 api 수정
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/HofController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/MemberController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/MemberRequestDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/enumType/ErrorCode.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/handler/CustomException.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/handler/ErrorResponse.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/handler/GlobalExceptionHandler.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/repository/HofRepository.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/repository/MemberRepository.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/HofService.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/MemberService.java
Labels: feature

#7 [#3] 파일명 수정
  .idea/uiDesigner.xml
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/HofController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/MemberController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/ProjectController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/response/BasicResponse.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/response/CommonResponse.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/hof/HofRequestDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/hof/HofResponseDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/member/MemberRequestDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/member/MemberResponseDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/project/ProjectRequestDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/project/ProjectResponseDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/project/ProjectSaveRequestDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/entity/Project.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/HofService.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/MemberService.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/ProjectService.java
  dogvelopers/src/main/resources/application.yml
Labels: refactor

#10 update , delete 기능 추가 및 , 조회기능 수정
  dogvelopers/build.gradle
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/HofController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/MemberController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/hof/HofResponseDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/hof/SortByDate.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/member/MemberRequestDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/member/MemberResponseDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/entity/Hof.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/entity/Member.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/repository/HofRepository.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/repository/MemberRepository.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/HofService.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/MemberService.java
  dogvelopers/src/main/resources/application.yml
  dogvelopers/src/test/java/com/dogvelopers/dogvelopers/controller/HofControllerTest.java
Labels: feature

#12 [#9] 생일 , 기수 자료형 변경 및 , 어드민 페이지 초안
  dogvelopers/build.gradle
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/HofController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/MemberController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/admin/adminController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/hof/SortByGeneration.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/member/MemberRequestDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/member/MemberResponseDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/entity/Member.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/repository/MemberRepository.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/HofService.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/MemberService.java
  dogvelopers/src/main/resources/templates/hofs/createHofForm.html
  dogvelopers/src/main/resources/templates/members/createMemberForm.html
  dogvelopers/src/main/resources/templates/projects/createProjectForm.html
Labels: feature

#14 테스트 코드 및 간단한 수정
  dogvelopers/build.gradle
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/ProjectController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/repository/ProjectRepository.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/ProjectService.java
  dogvelopers/src/main/resources/templates/projects/createProjectForm.html
  dogvelopers/src/test/java/com/dogvelopers/dogvelopers/controller/HofControllerTest.java
  dogvelopers/src/test/java/com/dogvelopers/dogvelopers/repository/ProjectRepositoryTest.java
  dogvelopers/src/test/resources/application.yml
Labels: refactor

#15 [#8] Project Service Test
  dogvelopers/src/test/java/com/dogvelopers/dogvelopers/service/ProjectServiceTest.java
Labels: feature

#16 [#9] admin page CRUD 전부 적용
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/MemberController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/admin/adminController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/hof/HofAdminDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/project/ProjectRequestDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/entity/Hof.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/entity/Member.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/entity/Project.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/HofService.java
  dogvelopers/src/main/resources/static/basic.css
  dogvelopers/src/main/resources/templates/hofs/createHofForm.html
  dogvelopers/src/main/resources/templates/members/createMemberForm.html
  dogvelopers/src/main/resources/templates/projects/createProjectForm.html
  dogvelopers/src/test/java/com/dogvelopers/dogvelopers/controller/HofControllerTest.java
Labels: feature, refactor

#17 Admin Refactoring
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/HofController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/MemberController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/admin/AdminHofController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/admin/AdminMemberController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/admin/AdminProjectController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/admin/adminController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/repository/HofRepository.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/repository/MemberRepository.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/repository/ProjectRepository.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/HofService.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/MemberService.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/ProjectService.java
  dogvelopers/src/main/resources/application.yml
Labels: refactor

#19 [#18] aws S3 bucket 설정과 , application-aws , credentials.yml 파일 gitignore 에 추가
  .gitignore
  dogveloper.sql
  dogvelopers/build.gradle
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/config/S3Config.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/MemberController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/admin/AdminHofController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/admin/AdminMemberController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/admin/AdminProjectController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/component/S3Component.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/member/MemberRequestDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/member/MemberResponseDto.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/entity/Member.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/enumType/ErrorCode.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/HofService.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/MemberService.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/image/AwsS3AwsS3UploadServiceImpl.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/image/AwsS3UploadService.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/service/image/FileUploadService.java
  dogvelopers/src/main/resources/application.yml
  dogvelopers/src/main/resources/templates/hofs/createHofForm.html
  dogvelopers/src/main/resources/templates/members/createMemberForm.html
Labels: feature

#21 [#8] Project 테스트 코드 작성 완료
  dogvelopers/build.gradle
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/controller/ProjectController.java
  dogvelopers/src/main/java/com/dogvelopers/dogvelopers/dto/project/ProjectSaveRequestDto.java
  dogvelopers/src/test/java/com/dogvelopers/dogvelopers/controller/ProjectControllerTest.java
Labels: feature
